branch-defaults:
  default:
    environment: aws-test-env
    group_suffix: null
  master:
    environment: aws-test-env
global:
  application_name: test-aws
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.3.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
